# MagicWells config file

# Database settings
databse:
  # If true, MW will use a MySQL database for storing well locations.  Database parameters must be specified below.
  enabled: false
  address: 127.0.0.1
  username: user
  password: pass
  table: magicwells
