# MagicWells config file

# Database settings
databse:
  # If true, MW will use a MySQL database for storing well locations.  Database parameters must be specified below.
  enabled: false
  address: 127.0.0.1
  username: user
  password: pass
  table: magicwells

# Chance of generating a well.
# 1.0 is 1 well in every chunk
well_gen_chance: 0.25f