# MagicWells config file

# Database settings
databse:
  # If true, MW will connect to an external database for storing well locations.  Database parameters must be specified below.
  external: false
  address: 127.0.0.1
  username: user
  password: pass
  table: magicwells

# Chance of generating a well.
# 1.0 is 1 well in every chunk
well_gen_chance: 0.15

# Blocks to avoid when generating
gen_avoid_blocks: [CHEST, END_GATEWAY]

# Percent of blocks that are already missing from a newly generated well
well_gen_damage: 0.0